# ./r-deployment.yml
$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: deployment-1
endpoint_name: experiment-1
code_configuration:
  code: ./src
  scoring_script: plumber.R
model: azureml:my-registered-timeseries-model@latest
environment:
  image: 0194711019b74feb8a030a1f78e227ae.azurecr.io/acr-container-for-plumber-deployment
  inference_config:
    liveness_route:
      port: 8000
      path: /live
    readiness_route:
      port: 8000
      path: /ready
    scoring_route:
      port: 8000
      path: /score
instance_type: Standard_DS2_v2
instance_count: 1