$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: 5b_env_registered
description: Pipeline job with component using a registered AzureML environment

jobs:
  hello_python_world_job:
    type: command
    component: azureml:hello_python_world:1
    compute: azureml:cpu-cluster
    environment: azureml:AzureML-sklearn-1.0-ubuntu20.04-py38-cpu:30

